"""
AI Command Executor for Proxmox
This module contains the logic to execute commands generated by the AI assistant.
"""
import json
from typing import Dict, Any


def execute_ai_command(
    command_json: Dict[str, Any],
    api_create_func,
    api_cluster_create_func,
    api_delete_func,
    api_list_func,
    log_telegram_func
) -> Dict[str, Any]:
    """
    Execute a command generated by the AI for Proxmox operations.
    
    Args:
        command_json: Dictionary with 'command', 'parameters', and 'explanation'
        api_create_func: Function to create VMs/containers
        api_cluster_create_func: Function to create clusters
        api_delete_func: Function to delete VMs/containers
        api_list_func: Function to list VMs/containers
        log_telegram_func: Function to log to Telegram
    
    Returns:
        Dictionary with execution result
    
    Supported commands:
        - create_vm: Create a single VM or LXC container
        - create_cluster: Create a Docker Swarm cluster
        - delete_vm: Delete VM(s) or container(s)
        - list_vms: List all VMs and containers
    """
    command = command_json.get("command")
    parameters = command_json.get("parameters", {})
    explanation = command_json.get("explanation", "")
    
    log_telegram_func(f"🤖 AI Command Execution: {command}\n{explanation}")
    
    if command == "create_vm":
        # Create a single VM or LXC container
        try:
            from main import ProxmoxCreateRequest
            
            # Set defaults if not provided
            vm_params = {
                "name": parameters.get("name", "ai-vm"),
                "vm_type": parameters.get("vm_type", "qemu"),
                "cores": parameters.get("cores", 2),
                "memory": parameters.get("memory", 2048),
                "disk_size": parameters.get("disk_size", 10),
                "cluster_type": parameters.get("cluster_type"),
                "count": parameters.get("count", 1),
                "node": parameters.get("node"),
                "template": parameters.get("template"),
                "iso": parameters.get("iso"),
                "lxc_template": parameters.get("lxc_template"),
                "storage": parameters.get("storage"),
                "bridge": parameters.get("bridge"),
                "ssh_key": parameters.get("ssh_key"),
                "password": parameters.get("password"),
                "start": parameters.get("start", True)
            }
            
            req = ProxmoxCreateRequest(**vm_params)
            result = api_create_func(req)
            
            return {
                "success": True,
                "command": command,
                "explanation": explanation,
                "result": result
            }
        except Exception as e:
            log_telegram_func(f"❌ Error creating VM: {e}")
            return {
                "success": False,
                "command": command,
                "explanation": explanation,
                "error": str(e)
            }
    
    elif command == "create_cluster":
        # Create a Docker Swarm cluster with manager and workers
        try:
            from main import ClusterCreateRequest, ProxmoxCreateRequest
            
            # Extract manager configuration
            manager_params = parameters.get("manager", {})
            manager = ProxmoxCreateRequest(
                name=manager_params.get("name", "swarm-manager"),
                vm_type=manager_params.get("vm_type", "qemu"),
                cores=manager_params.get("cores", 2),
                memory=manager_params.get("memory", 2048),
                disk_size=manager_params.get("disk_size", 20),
                node=manager_params.get("node"),
                template=manager_params.get("template"),
                iso=manager_params.get("iso"),
                storage=manager_params.get("storage"),
                bridge=manager_params.get("bridge")
            )
            
            # Extract workers configuration
            workers = []
            workers_params = parameters.get("workers", [])
            for worker_param in workers_params:
                worker = ProxmoxCreateRequest(
                    name=worker_param.get("name", "swarm-worker"),
                    vm_type=worker_param.get("vm_type", "lxc"),
                    cores=worker_param.get("cores", 1),
                    memory=worker_param.get("memory", 1024),
                    disk_size=worker_param.get("disk_size", 10),
                    count=worker_param.get("count", 1),
                    node=worker_param.get("node"),
                    template=worker_param.get("template"),
                    lxc_template=worker_param.get("lxc_template"),
                    storage=worker_param.get("storage"),
                    bridge=worker_param.get("bridge")
                )
                workers.append(worker)
            
            # Create cluster request
            cluster_req = ClusterCreateRequest(
                manager=manager,
                workers=workers if workers else None,
                total_nodes=parameters.get("total_nodes")
            )
            
            result = api_cluster_create_func(cluster_req)
            
            return {
                "success": True,
                "command": command,
                "explanation": explanation,
                "result": result
            }
        except Exception as e:
            log_telegram_func(f"❌ Error creating cluster: {e}")
            return {
                "success": False,
                "command": command,
                "explanation": explanation,
                "error": str(e)
            }
    
    elif command == "delete_vm":
        # Delete one or more VMs/containers
        try:
            from main import ProxmoxDeleteRequest
            
            results = {}
            
            # Handle list of VMs/containers
            vms_to_delete = parameters.get("vms", [])
            if vms_to_delete:
                for vm in vms_to_delete:
                    vm_name = vm.get("name")
                    vmid = vm.get("vmid")
                    node = vm.get("node")
                    
                    try:
                        delete_req = ProxmoxDeleteRequest(
                            vmid=vmid,
                            name=vm_name,
                            node=node,
                            force=True
                        )
                        results[vm_name or f"vmid-{vmid}"] = api_delete_func(delete_req)
                    except Exception as e:
                        results[vm_name or f"vmid-{vmid}"] = {"error": str(e)}
            
            # Handle single VM/container
            elif parameters.get("name") or parameters.get("vmid"):
                delete_req = ProxmoxDeleteRequest(
                    vmid=parameters.get("vmid"),
                    name=parameters.get("name"),
                    node=parameters.get("node"),
                    force=parameters.get("force", True)
                )
                result = api_delete_func(delete_req)
                results["single"] = result
            
            return {
                "success": True,
                "command": command,
                "explanation": explanation,
                "result": results
            }
        except Exception as e:
            log_telegram_func(f"❌ Error deleting VM: {e}")
            return {
                "success": False,
                "command": command,
                "explanation": explanation,
                "error": str(e)
            }
    
    elif command == "list_vms":
        # List all VMs and containers
        try:
            from main import ProxmoxListRequest
            
            list_req = ProxmoxListRequest(
                node=parameters.get("node"),
                status=parameters.get("status"),
                vm_type=parameters.get("vm_type")
            )
            
            result = api_list_func(list_req)
            
            return {
                "success": True,
                "command": command,
                "explanation": explanation,
                "result": result
            }
        except Exception as e:
            log_telegram_func(f"❌ Error listing VMs: {e}")
            return {
                "success": False,
                "command": command,
                "explanation": explanation,
                "error": str(e)
            }
    
    else:
        error_msg = f"Unknown command: {command}"
        log_telegram_func(f"❌ {error_msg}")
        raise ValueError(error_msg)
